### ISSUE TITLE
Terminal client from master has some issues rendering anything

### ISSUE THREAD

**Issue by jaseg** [hzeller/flaschen-taschen#19]
Using master, the terminal client produces output like this for all clients I tried (send-image, send-video and the pnmfoo bash thingy from the readme):
![screenshot](http://i.imgur.com/f0YkYLe.png)

**Comment by hzeller** [comment]
This looks odd. It definitely works with master out of the box for the following terminals I tested
- XTerm(304)
- Konsole 2.14.1
- Gnome terminal 3.6.2

(On a Mac, people have success with iTerm2 3.0 beta)

I have seen that in your pull request #20 (are you using that code for your test?), you add an alpha-channel field in struct Color. Since this struct is also used on the client side as the type kept in the PNM buffer, this won't work well: now the whole sizeof(Color) of course changes to 4, the pixel-buffer size in udp-flaschen-taschen.cc also changes and the result is not a valid PPM anymore.
It looks like things are shifted around in your output which could be due to that.

**Comment by hzeller** [comment]
I've tested that hypothesis and, yes, changing sizeof(Color) will mess up things: the UDPFlaschenTaschen uses that as internal type to lay out the buffer to send in memory.

Next to separating the types, I suppose within the HD terminal change, you can just keep struct Color as is (because the alpha channel is - at this point - never needed outside the terminal code), and just assume defaults in the YUV code (or: if you get rid of the alpha channel in general, the whole detour through YUV is not needed anymore).

**Comment by hzeller** [comment]
I suspect that was due to the changed struct Color size in the modified branch. Please re-open if you see trouble with a fresh checkout from head.
