### ISSUE TITLE
Regarding client code

### ISSUE THREAD

**Issue by noorabrar1** [hzeller/flaschen-taschen#34]
I wanted to run client code from my laptop(ubuntu), and server as Raspberry pi 3, as in raspbery both client and server code working fine. 
but in system i'm getting error while making client file.
error is:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

can you please help me out of this

**Comment by hzeller** [comment]
Can you do a fresh git pull and try again ?

**Comment by noorabrar1** [comment]
Thanks for replay sir.. i cloned and tried for 3 times.. same result,... actually i am new here, i dot know how to pull, is that same as clone??..  please can you guide me on this...

**Comment by hzeller** [comment]
`git pull` you do in the directory that you already had cloned to get the latest version.
`git clone` is what you do to do a fresh checkout.

So if your error was in the bdf-font before, then with the current version you can't get the same error message, because the file in question is not even included anymore. If you get another error, please provide a little bit more context (e.g. the name of the file that was compiled and generated the error)

**Comment by noorabrar1** [comment]
hello sir,

Thanks for info, got some knowledge.. zero errors, it worked, but only sent-text file appeared.. other image and video file missing from client folder... anyhow i wanted only send-text file.. thanks for help sir.  and final question y those two file disappeared?????
