### ISSUE TITLE
P5 16s-Scroll to Static

### ISSUE THREAD

**Issue by HummingBuddha** [hzeller/flaschen-taschen#37]
Hello Hzeller

I am trying to make the scroll fields static. "./send-text -h localhost "Flaschen" -f fonts/10x20.bdf -s 20 -g 288x64+64+10+1" . I have tried with '-s 0', but it works for 10-15 seconds. I am trying for an infinite static . Please guide me in this issue.

**Comment by hzeller** [comment]
the 10 seconds are just the layer timeout on the server (`--layer-timeout`): if nothing is happening on a layer, the layer is garbage collected, so that nobody can hog a layer forever by sending a single packet and walking away. Only layer 0 stays forever.
If you don't need this do one of the following

  * Send it to layer 0. That never gets garbage collected
  * For other layers: Regularly refresh the content before the timeout occurs.
  * If you're running your own installation (and we're not talking about the public installation at Noisebridge): Set the `--layer-timeout` on the server to a very long time or [even comment out the garbage collector start](https://github.com/hzeller/flaschen-taschen/blob/master/server/main.cc#L231).

**Comment by HummingBuddha** [comment]
Hey Hzeller
Thanks once again it worked out.
