### ISSUE TITLE
Only able to control led strings on SPI_P2 and SPI_P13. 

### ISSUE THREAD

**Issue by dwright213** [hzeller/flaschen-taschen#42]
I checked all my solders (I'm using the spixels board), and all the connectors have solid continuity from their pins to the 74HCT245's pins.

This has been a persistent problem though, across 2 spixels boards (the other board I put together just for testing, only used one 74HCT245, and only SPI_P2 was working). 2 different rpis (3b and  3b+), and quite a few Raspbian lite installations, so my only guess is that the cause is some difference in gpio/spi functionality between the rpi2 and rpi3. 

I could be way off, I am not sure what else I should be testing though, at this point. Any ideas?

**Comment by hzeller** [comment]
mmh, so you are a bit sparse with the information you provide.

- Which version of the Spixels board are you using ? (typically 2016-05-07 I guess). All should work, but I had speciality versions handed out as well, so knowing the reference is good.
- I suppose, clock also works ? Otherwise you would not see any LED strip update on P2/P13.
- Do you see the same problem with the DMA or direct-multi SPI ?
- Are you using FlaschenTaschen or the Spixel library directly ?
- What kind of LED strips are you using ? WS2801, APA102 or LDP6803
- If you have a newer Pi make sure to use the spixels version newer than May or so as there was a workaround needed (version >= https://github.com/hzeller/spixels/commit/900127ac396804c6d7fc9c8a01ed812f6f8dc7f3 )
- did you disable other things that might interfere with the GPIOs ? 1 wire connection, no pigpio etc. might mess with the system (generally it is a good idea to use a minimal raspbian lite version if you have not already).

**Comment by dwright213** [comment]
Sorry about that, I'll fill you in.
 
- I am using the 05-07-2016 board.
- I'm not sure how to check if clock works (check dc voltage on the SCLK pin?) but I figured that the ports that are working would indicate that.
- I haven't tried using CreateDirectMultiSPI, only CreateDMAMultiSPI, due to the advice of  spixels/examples/simple.cc, where it says:
`    // If you are using WS2801, then you need CreateDMAMultiSPI() instead,
    // as these strips are finicky with timings.
` 
- I am using FlaschenTaschen with the Spixels library.
- The LED strip type I am using is WS2801.
- Affirmative, I definitely made sure I am using the latest version of both Spixels and FlaschenTaschen.

And I will go ahead and check that nothing else is messing with the gpio..

**Comment by dwright213** [comment]
Update:
I disabled i2c and "remote gpio" with the raspi-config utility, so I guess I did indeed have pigpio running.

I also installed wiringPi (which I probably need to uninstall now). Before turning off remote gpio (and with ft_server running) , wiringPi's readall command gave me the following, if it's helpful:

(edit: removed, markdown doesn't keep original formatting, making it kind of gibberish)

**Comment by hzeller** [comment]
So did it work after you simplified the installation ?

**Comment by dwright213** [comment]
Yes! Sorry for the lack of response, it's been crunch time on this project, so I've been putting lots of work in. 

It may have been my installation, but I think it was actually my soldering and testing skills that were the problem, because after resoldering and testing each leg of the level shifters, I was able to get them working. Sorry to pester you with it, this project has been a comedy of errors for me.

Unrelated, but I have an Ansible project for Flaschen Taschen, to standardize pi setup and simplify code pushing. Maybe someone else browsing the issues could use it.

https://github.com/dwright213/ft-deploy
